#
# DO NOT EDIT THIS FILE MANUALLY!
#
# To update, call `bazel run @rules_ros//repos/config:repos_lock.update` with the right distro set in the WORKSPACE
#
# SHA256 of external/ros2/ros2.repos: 39f46bd1062a88c4f48a23ce96dcf3df8851fa45dd714d40fa5e606fa2040480

load("@bazel_tools//tools/build_defs/repo:utils.bzl", _maybe = "maybe")
load("@rules_ros//repos/config/detail:git_repository.bzl", "git_repository")
load("@rules_ros//repos/config/detail:http_archive.bzl", "http_archive")
load("@rules_ros//repos/config/detail:new_local_repository.bzl", "new_local_repository")

def setup():
    pass

    _maybe(
        name = "ament.ament_index",
        branch = "1.2.0",
        build_files = {
            "@rules_ros//repos:ament.ament_index/ament_index_cpp.BUILD": "ament_index_cpp/BUILD.bazel",
            "@rules_ros//repos:ament.ament_index/ament_index_python.BUILD": "ament_index_python/BUILD.bazel",
        },
        commit = "7c8a2762453bf928909cc3dd65d2164b2f67dbaf",
        remote = "https://github.com/ament/ament_index.git",
        repo_rule = git_repository,
        shallow_since = "1625088463 -0700",
    )

    _maybe(
        name = "eProsima.Fast-CDR",
        branch = "v1.0.20",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "53a0b8cae0b9083db69821be0edb97c944755591",
        remote = "https://github.com/eProsima/Fast-CDR.git",
        repo_rule = git_repository,
        shallow_since = "1613980210 +0100",
    )

    _maybe(
        name = "eProsima.Fast-DDS",
        branch = "v2.3.6",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "a53c921c67cc3691950486dd52ef609e5da391c0",
        remote = "https://github.com/eProsima/Fast-DDS.git",
        repo_rule = git_repository,
        shallow_since = "1669279458 +0100",
    )

    _maybe(
        name = "eProsima.foonathan_memory_vendor",
        branch = "v1.2.0",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "da062db05975d24a4b53de5a4122b47f6824997f",
        remote = "https://github.com/eProsima/foonathan_memory_vendor.git",
        repo_rule = git_repository,
        shallow_since = "1637848987 +0100",
    )

    _maybe(
        name = "eclipse-cyclonedds.cyclonedds",
        branch = "0.8.0",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "7465083759ef8ee2e119b3ee5ab6fd76ad8dc902",
        remote = "https://github.com/eclipse-cyclonedds/cyclonedds.git",
        repo_rule = git_repository,
        shallow_since = "1631118613 +0200",
    )

    _maybe(
        name = "eclipse-iceoryx.iceoryx",
        branch = "v1.0.0",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "2921d44025461930ab7707e541f26f2d77343871",
        remote = "https://github.com/eclipse-iceoryx/iceoryx.git",
        repo_rule = git_repository,
        shallow_since = "1618512644 +0200",
    )

    _maybe(
        name = "ros-tooling.libstatistics_collector",
        branch = "1.1.1",
        build_files = {
            "@rules_ros//repos:ros-tooling.libstatistics_collector/root.BUILD": "BUILD.bazel",
        },
        commit = "db5f90805c6f8b40e50c15b853cc040d491e5336",
        remote = "https://github.com/ros-tooling/libstatistics_collector.git",
        repo_rule = git_repository,
        shallow_since = "1628188927 -0700",
    )

    _maybe(
        name = "ros2.common_interfaces",
        branch = "2.2.4",
        build_files = {
            "@rules_ros//repos:ros2.common_interfaces/std_msgs.BUILD": "std_msgs/BUILD.bazel",
        },
        commit = "969a56b0b59f7f70b5c4561185ea34aaa2b74e1d",
        remote = "https://github.com/ros2/common_interfaces.git",
        repo_rule = git_repository,
        shallow_since = "1641946918 +0000",
    )

    _maybe(
        name = "ros2.rcl",
        branch = "3.1.4",
        build_files = {
            "@rules_ros//repos:ros2.rcl/rcl.BUILD": "rcl/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl/rcl_yaml_param_parser.BUILD": "rcl_yaml_param_parser/BUILD.bazel",
        },
        commit = "160039d038130ce515dd204bd050a414c63b5dd4",
        remote = "https://github.com/ros2/rcl.git",
        repo_rule = git_repository,
        shallow_since = "1670039598 -0800",
    )

    _maybe(
        name = "ros2.rcl_interfaces",
        branch = "1.0.3",
        build_files = {
            "@rules_ros//repos:ros2.rcl_interfaces/rcl_interfaces.BUILD": "rcl_interfaces/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl_interfaces/rosgraph_msgs.BUILD": "rosgraph_msgs/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl_interfaces/builtin_interfaces.BUILD": "builtin_interfaces/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl_interfaces/statistics_msgs.BUILD": "statistics_msgs/BUILD.bazel",
        },
        commit = "c5d0a20150533a6cb93d5dcbd6e27cea9300aa6e",
        remote = "https://github.com/ros2/rcl_interfaces.git",
        repo_rule = git_repository,
        shallow_since = "1617722105 +0000",
    )

    _maybe(
        name = "ros2.rcl_logging",
        branch = "2.1.5",
        build_files = {
            "@rules_ros//repos:ros2.rcl_logging/rcl_logging_interface.BUILD": "rcl_logging_interface/BUILD.bazel",
        },
        commit = "48d9680111e4d53440cc7e830a53eabbbe98f94b",
        remote = "https://github.com/ros2/rcl_logging.git",
        repo_rule = git_repository,
        shallow_since = "1670035329 -0800",
    )

    _maybe(
        name = "ros2.rclcpp",
        branch = "9.2.2",
        build_files = {
            "@rules_ros//repos:ros2.rclcpp/build_interfaces.py": "rclcpp/build_interfaces.py",
            "@rules_ros//repos:ros2.rclcpp/rclcpp.BUILD": "rclcpp/BUILD.bazel",
        },
        commit = "7aff0ffc56b8875ceb7af6e5beb832721fffed19",
        remote = "https://github.com/ros2/rclcpp.git",
        repo_rule = git_repository,
        shallow_since = "1670378370 -0800",
    )

    _maybe(
        name = "ros2.rcpputils",
        branch = "2.2.2",
        build_files = {
            "@rules_ros//repos:ros2.rcpputils/rcpputils.BUILD": "BUILD.bazel",
        },
        commit = "a84bb6630b8c885592a44913fde082fae3121765",
        remote = "https://github.com/ros2/rcpputils.git",
        repo_rule = git_repository,
        shallow_since = "1670034511 -0800",
    )

    _maybe(
        name = "ros2.rcutils",
        branch = "4.0.4",
        build_files = {
            "@rules_ros//repos:ros2.rcutils/root.BUILD": "BUILD.bazel",
            "@rules_ros//repos:ros2.rcutils/build_logging_macros.py": "build_logging_macros.py",
        },
        commit = "cf8554fab36d971ba2c855b98ae8f6195d1a7071",
        remote = "https://github.com/ros2/rcutils.git",
        repo_rule = git_repository,
        shallow_since = "1670033868 -0800",
    )

    _maybe(
        name = "ros2.rmw",
        branch = "3.3.1",
        build_files = {
            "@rules_ros//repos:ros2.rmw/rmw.BUILD": "rmw/BUILD.bazel",
        },
        commit = "f9f4ef46f8dd3ef938526a1140a3c57c155a259f",
        remote = "https://github.com/ros2/rmw.git",
        repo_rule = git_repository,
        shallow_since = "1619470129 +0000",
    )

    _maybe(
        name = "ros2.ros2_tracing",
        branch = "2.3.0",
        build_files = {
            "@rules_ros//repos:ros2.ros2_tracing/tracetools.BUILD": "tracetools/BUILD.bazel",
        },
        commit = "a21e07155da8ea68c1e3498d436742c24e2072ec",
        remote = "https://github.com/ros2/ros2_tracing.git",
        repo_rule = git_repository,
        shallow_since = "1617197866 -0400",
    )

    _maybe(
        name = "ros2.ros2cli",
        branch = "0.13.5",
        build_files = {
            "@rules_ros//repos:ros2.ros2cli/ros2cli.BUILD": "ros2cli/BUILD.bazel",
            "@rules_ros//repos:ros2.ros2cli/ros2pkg.BUILD": "ros2pkg/BUILD.bazel",
            "@rules_ros//repos:ros2.ros2cli/ros2run.BUILD": "ros2run/BUILD.bazel",
        },
        commit = "1c68ba9cd3bb68584e7abfd4014818d9ea999e0b",
        remote = "https://github.com/ros2/ros2cli.git",
        repo_rule = git_repository,
        shallow_since = "1670041713 -0800",
    )

    _maybe(
        name = "ros2.rosidl",
        branch = "2.2.3",
        build_files = {
            "@rules_ros//repos:ros2.rosidl/rosidl_runtime_c.BUILD": "rosidl_runtime_c/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_runtime_cpp.BUILD": "rosidl_runtime_cpp/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_adapter.BUILD": "rosidl_adapter/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_cli.BUILD": "rosidl_cli/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_parser.BUILD": "rosidl_parser/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_cmake.BUILD": "rosidl_cmake/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_typesupport_interface.BUILD": "rosidl_typesupport_interface/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_generator_c.BUILD": "rosidl_generator_c/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_generator_cpp.BUILD": "rosidl_generator_cpp/BUILD.bazel",
        },
        commit = "3be0e4db59979c7b74b50e2778cdd5c700e3b248",
        remote = "https://github.com/ros2/rosidl.git",
        repo_rule = git_repository,
        shallow_since = "1670026799 -0800",
    )

    _maybe(
        name = "ros2.rosidl_dds",
        branch = "0.8.0",
        build_files = {
            "@rules_ros//repos:ros2.rosidl_dds/rosidl_generator_dds_idl.BUILD": "rosidl_generator_dds_idl/BUILD.bazel",
        },
        commit = "9831bdd56052aeb0ddf1454e0e7100c64905f556",
        remote = "https://github.com/ros2/rosidl_dds.git",
        repo_rule = git_repository,
        shallow_since = "1616186809 +0000",
    )

    _maybe(
        name = "ros2.rosidl_typesupport",
        branch = "1.2.1",
        build_files = {
            "@rules_ros//repos:ros2.rosidl_typesupport/rosidl_typesupport_c.BUILD": "rosidl_typesupport_c/BUILD.bazel",
        },
        commit = "3bd7d816e62ec05390af09a761ea3e0d7bb7b9a6",
        remote = "https://github.com/ros2/rosidl_typesupport.git",
        repo_rule = git_repository,
        shallow_since = "1617720611 +0000",
    )
