#
# DO NOT EDIT THIS FILE MANUALLY!
#
# To update, call `bazel run @rules_ros//repos/config:repos_lock.update` with the right distro set in the WORKSPACE
#
# SHA256 of external/ros2/ros2.repos: 980239e9346bd1388a0b0e5d2d989c0deccbe75df5985b27d4207efa7cf7cd82

load("@bazel_tools//tools/build_defs/repo:utils.bzl", _maybe = "maybe")
load("@rules_ros//repos/config/detail:git_repository.bzl", "git_repository")
load("@rules_ros//repos/config/detail:http_archive.bzl", "http_archive")
load("@rules_ros//repos/config/detail:new_local_repository.bzl", "new_local_repository")

def setup():
    pass

    _maybe(
        name = "ament.ament_index",
        branch = "1.8.1",
        build_files = {
            "@rules_ros//repos:ament.ament_index/ament_index_cpp.BUILD": "ament_index_cpp/BUILD.bazel",
            "@rules_ros//repos:ament.ament_index/ament_index_python.BUILD": "ament_index_python/BUILD.bazel",
        },
        commit = "0ed743ad9e3b583d975ffcde0b57de8a0b1204ae",
        remote = "https://github.com/ament/ament_index.git",
        repo_rule = git_repository,
        shallow_since = "1713977502 +0000",
    )

    _maybe(
        name = "eProsima.Fast-CDR",
        branch = "v2.2.4",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "c00d31c36375c3f4b5e0926d3046bfde5f63ff14",
        remote = "https://github.com/eProsima/Fast-CDR.git",
        repo_rule = git_repository,
        shallow_since = "1725964513 +0200",
    )

    _maybe(
        name = "eProsima.Fast-DDS",
        branch = "v2.14.1",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "ffd9476e08b6fc201c46e7012af3127d7eb0bbb6",
        remote = "https://github.com/eProsima/Fast-DDS.git",
        repo_rule = git_repository,
        shallow_since = "1715582395 +0200",
    )

    _maybe(
        name = "eProsima.foonathan_memory_vendor",
        branch = "v1.3.1",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "e91681a25711c1811b2eaf2ba1e6996e0d9ecc84",
        remote = "https://github.com/eProsima/foonathan_memory_vendor.git",
        repo_rule = git_repository,
        shallow_since = "1683727792 +0200",
    )

    _maybe(
        name = "eclipse-cyclonedds.cyclonedds",
        branch = "0.10.5",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "2cdd114cbd18340c606573b4cc8dc20cc161ec5a",
        remote = "https://github.com/eclipse-cyclonedds/cyclonedds.git",
        repo_rule = git_repository,
        shallow_since = "1715939482 +0200",
    )

    _maybe(
        name = "eclipse-iceoryx.iceoryx",
        branch = "v2.0.5",
        build_files = {
            "@rules_ros//repos:default.BUILD": "BUILD.bazel",
        },
        commit = "e274957ac619cd9881687e688e3f8d1c28ff115c",
        remote = "https://github.com/eclipse-iceoryx/iceoryx.git",
        repo_rule = git_repository,
        shallow_since = "1701698577 +0100",
    )

    _maybe(
        name = "ros-tooling.libstatistics_collector",
        branch = "1.7.3",
        build_files = {
            "@rules_ros//repos:ros-tooling.libstatistics_collector/root.BUILD": "BUILD.bazel",
        },
        commit = "df4e05887517486ce8325a58d39fc25a5caa3000",
        remote = "https://github.com/ros-tooling/libstatistics_collector.git",
        repo_rule = git_repository,
        shallow_since = "1719261482 -0700",
    )

    _maybe(
        name = "ros2.common_interfaces",
        branch = "5.3.5",
        build_files = {
            "@rules_ros//repos:ros2.common_interfaces/std_msgs.BUILD": "std_msgs/BUILD.bazel",
        },
        commit = "b8539bfd4419fd33612d7b72d7ccf20d7ec9f402",
        remote = "https://github.com/ros2/common_interfaces.git",
        repo_rule = git_repository,
        shallow_since = "1713978550 +0000",
    )

    _maybe(
        name = "ros2.rcl",
        branch = "9.2.4",
        build_files = {
            "@rules_ros//repos:ros2.rcl/rcl.BUILD": "rcl/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl/rcl_yaml_param_parser.BUILD": "rcl_yaml_param_parser/BUILD.bazel",
        },
        commit = "7927b7649b2f1089c87492ed6b22a919a5d0dbed",
        remote = "https://github.com/ros2/rcl.git",
        repo_rule = git_repository,
        shallow_since = "1726766379 +0000",
    )

    _maybe(
        name = "ros2.rcl_interfaces",
        branch = "2.0.2",
        build_files = {
            "@rules_ros//repos:ros2.rcl_interfaces/rcl_interfaces.BUILD": "rcl_interfaces/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl_interfaces/rosgraph_msgs.BUILD": "rosgraph_msgs/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl_interfaces/builtin_interfaces.BUILD": "builtin_interfaces/BUILD.bazel",
            "@rules_ros//repos:ros2.rcl_interfaces/statistics_msgs.BUILD": "statistics_msgs/BUILD.bazel",
        },
        commit = "003987ecb81a32802ab27dd6d325b8c6b8b813cc",
        remote = "https://github.com/ros2/rcl_interfaces.git",
        repo_rule = git_repository,
        shallow_since = "1713274861 +0200",
    )

    _maybe(
        name = "ros2.rcl_logging",
        branch = "3.1.0",
        build_files = {
            "@rules_ros//repos:ros2.rcl_logging/rcl_logging_interface.BUILD": "rcl_logging_interface/BUILD.bazel",
        },
        commit = "128d88e6e4ad6df97405564afbdffa2ebc167814",
        remote = "https://github.com/ros2/rcl_logging.git",
        repo_rule = git_repository,
        shallow_since = "1711616195 +0000",
    )

    _maybe(
        name = "ros2.rclcpp",
        branch = "28.1.5",
        build_files = {
            "@rules_ros//repos:ros2.rclcpp/build_interfaces.py": "rclcpp/build_interfaces.py",
            "@rules_ros//repos:ros2.rclcpp/rclcpp.BUILD": "rclcpp/BUILD.bazel",
        },
        commit = "09e5dd70f4c1f4cf7809b858e3b8e7f22c336980",
        remote = "https://github.com/ros2/rclcpp.git",
        repo_rule = git_repository,
        shallow_since = "1726766153 +0000",
    )

    _maybe(
        name = "ros2.rcpputils",
        branch = "2.11.0",
        build_files = {
            "@rules_ros//repos:ros2.rcpputils/rcpputils.BUILD": "BUILD.bazel",
        },
        commit = "747b92f911cc3b338b6a73ad880e95c6be17075d",
        remote = "https://github.com/ros2/rcpputils.git",
        repo_rule = git_repository,
        shallow_since = "1713285186 +0200",
    )

    _maybe(
        name = "ros2.rcutils",
        branch = "6.7.2",
        build_files = {
            "@rules_ros//repos:ros2.rcutils/root.BUILD": "BUILD.bazel",
            "@rules_ros//repos:ros2.rcutils/build_logging_macros.py": "build_logging_macros.py",
        },
        commit = "2cd95ae7e8a0f752cc1ef75b71703552c0453a26",
        remote = "https://github.com/ros2/rcutils.git",
        repo_rule = git_repository,
        shallow_since = "1726605013 +0200",
    )

    _maybe(
        name = "ros2.rmw",
        branch = "7.3.1",
        build_files = {
            "@rules_ros//repos:ros2.rmw/rmw.BUILD": "rmw/BUILD.bazel",
        },
        commit = "c90c29700291eb975688326a31f8915803cf277d",
        remote = "https://github.com/ros2/rmw.git",
        repo_rule = git_repository,
        shallow_since = "1713977951 +0000",
    )

    _maybe(
        name = "ros2.ros2_tracing",
        branch = "8.2.2",
        build_files = {
            "@rules_ros//repos:ros2.ros2_tracing/tracetools.BUILD": "tracetools/BUILD.bazel",
        },
        commit = "5ee6af88401aebaf6761009ffbafac22ebe27972",
        remote = "https://github.com/ros2/ros2_tracing.git",
        repo_rule = git_repository,
        shallow_since = "1725646834 +0000",
    )

    _maybe(
        name = "ros2.ros2cli",
        branch = "0.32.1",
        build_files = {
            "@rules_ros//repos:ros2.ros2cli/ros2cli.BUILD": "ros2cli/BUILD.bazel",
            "@rules_ros//repos:ros2.ros2cli/ros2pkg.BUILD": "ros2pkg/BUILD.bazel",
            "@rules_ros//repos:ros2.ros2cli/ros2run.BUILD": "ros2run/BUILD.bazel",
        },
        commit = "ca159982040213d0e5cd100d3e4a400172952af5",
        remote = "https://github.com/ros2/ros2cli.git",
        repo_rule = git_repository,
        shallow_since = "1715636127 +0000",
    )

    _maybe(
        name = "ros2.rosidl",
        branch = "4.6.4",
        build_files = {
            "@rules_ros//repos:ros2.rosidl/rosidl_runtime_c.BUILD": "rosidl_runtime_c/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_runtime_cpp.BUILD": "rosidl_runtime_cpp/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_adapter.BUILD": "rosidl_adapter/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_cli.BUILD": "rosidl_cli/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_parser.BUILD": "rosidl_parser/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_cmake.BUILD": "rosidl_cmake/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_typesupport_interface.BUILD": "rosidl_typesupport_interface/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_generator_c.BUILD": "rosidl_generator_c/BUILD.bazel",
            "@rules_ros//repos:ros2.rosidl/rosidl_generator_cpp.BUILD": "rosidl_generator_cpp/BUILD.bazel",
        },
        commit = "b848d6c69abe2af6da8bc571647e03f7c5f867e0",
        remote = "https://github.com/ros2/rosidl.git",
        repo_rule = git_repository,
        shallow_since = "1725642240 +0000",
    )

    _maybe(
        name = "ros2.rosidl_dds",
        branch = "0.11.1",
        build_files = {
            "@rules_ros//repos:ros2.rosidl_dds/rosidl_generator_dds_idl.BUILD": "rosidl_generator_dds_idl/BUILD.bazel",
        },
        commit = "8d6fdb365792c81861cf1d49da2d265e91dca86d",
        remote = "https://github.com/ros2/rosidl_dds.git",
        repo_rule = git_repository,
        shallow_since = "1707312645 +0000",
    )

    _maybe(
        name = "ros2.rosidl_typesupport",
        branch = "3.2.2",
        build_files = {
            "@rules_ros//repos:ros2.rosidl_typesupport/rosidl_typesupport_c.BUILD": "rosidl_typesupport_c/BUILD.bazel",
        },
        commit = "dc851e02da9301718c22bf22bda7398fb41d4754",
        remote = "https://github.com/ros2/rosidl_typesupport.git",
        repo_rule = git_repository,
        shallow_since = "1713977601 +0000",
    )
