name: Build/Test

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

# only run one build doc workflow at a time, cancel any running ones
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    strategy:
      matrix:
        os:
          - ubuntu
        version:
          - 20.04
          - 22.04
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Specify the Bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ hashFiles('.bazelrc', '.bazelversion', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
      - name: Install buildifier
        run: |
          curl -f -s -L -o /usr/local/bin/buildifier https://github.com/bazelbuild/buildtools/releases/download/v7.3.1/buildifier-linux-$(arch | sed 's/aarch64/arm64/;s/x86_64/amd64/')
          chmod a+x /usr/local/bin/buildifier
      - name: Run buildifier
        run: buildifier -mode check -r .
      - name: Build
        # TODO(evan.flynn): uncomment once the rules are properly fixed
        # run: bazel build //...
        run: bazel build -- $(cat repos/config/bazel.repos | sed -e '/^[#r]/d' -e '/^    /d' -e 's%/%.%' -e 's%  \(.*\):%@\1//...%' -e '/@ros2.rosidl/d' -e '/@ros2.rcl_interfaces/d' -e '/@ros2.common_interfaces/d')
      - name: Test
        run: bazel test -- $(cat repos/config/bazel.repos | sed -e '/^[#r]/d' -e '/^    /d' -e 's%/%.%' -e 's%  \(.*\):%@\1//...%' -e '/@ros2.rosidl/d' -e '/@ros2.rcl_interfaces/d' -e '/@ros2.common_interfaces/d')
      - name: Store the bazel-testlogs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-bazel-testlogs
          path: bazel-testlogs
          retention-days: 5